### ISSUE TITLE
Tillägg i main.py

### ISSUE THREAD

**Issue by edunfelt** [RickyLake/PyDevOps#13]
Hej,

För att få formulärdata att sparas när man har fyllt i den sista sidan behövs nu följande tillägg:
- `from save_data import *`
- `def selectNext(page):`
`tabMenu.select(page)`
`if page == 3:`
`    data = {**page1.fields, **page2_content.fields, **page3_content.fields}`
`    save_data(data)`

:tada:

**Comment by RickyLake** [comment]
Request applied in GUI branch and has been merged to master branch.
