### ISSUE TITLE
Set limit for delmoment widget

### ISSUE THREAD

**Issue by RickyLake** [RickyLake/PyDevOps#18]
Either set a limit for delmoment widget or make it so that the user can't input values. If a user inputs the value of 1000, the software ends up freezing.

@edunfelt

**Comment by edunfelt** [comment]
Gjorde lite efterforskningar i docs om detta och kom fram till att det bästa blir att ändra i guiLib.py:
- `Spinbox.__init__(self, master, from_ = lowest, to = highest, state = "readonly", readonlybackground = "white", bg="white", textvariable = textvar, *args)`

Tillägget av `readonly` gör det möjligt att ta bort möjligheten att manuellt ändra i fältet, och man måste använda knapparna.

**Comment by RickyLake** [comment]
Very nice, issue has been fixed, awaiting for merge :+1:
