### ISSUE TITLE
Ändringar i main.py för inkudering av sida 2

### ISSUE THREAD

**Issue by edunfelt** [RickyLake/PyDevOps#8]
Hej!

Har experimenterat lokalt med `main.py` för att se hur sida 2 kan inkluderas och kommit fram till följande ändringar som behövs för att kunna merga min kod imorgon:

- `from second_page import *`
- frame för sida 2 (en för frame och en för att läsa in klassen):
`page2 = Frame(tabMenu, bg="white")`
    `page2_content = SecondPage(page2)`
- ändra ordningen på next och previous buttons, samt göra detta med pack:
`nextButtonPage2.pack(side = RIGHT, anchor = S)`
`previousButtonPage2.pack(side = RIGHT, anchor = S)`

Fick lägga min frame nästlad eftersom jag använt pack istället för grid, och det var även därför vissa ändringar behövdes för knapparna. Utseendet är däremot oförändrat från tidigare. 

Kul att se hur projektet börjar bli en helhet!

**Comment by RickyLake** [comment]
Applied requested changes in GUI branch, awaiting merge.
