### ISSUE TITLE
Ytterligare tillägg i guiLib.py

### ISSUE THREAD

**Issue by edunfelt** [RickyLake/PyDevOps#9]
Hej,

Hittade ytterligare några saker som gör stor skillnad (i min del av formuläret) om dessa fixas i `guiLib.py`. Testat lokalt och inga ytterligare delar av formuläret påverkas av detta.

- i klassen `forumInfo`, detta gör att texterna blir vänsterjusterade och lika långa (där detta syns):
`Label.__init__(self, master, font='Helvetica 11', bg="white", text=labelText, anchor="w", width = 20)`
- i klassen `mainFieldButton`, gjorde typsnittet en punkt större (samma som övriga fält):
`Radiobutton.__init__(self, master,text=labelText,font='Helvetica 11', bg="white", fg="darkblue", variable = Variable, value=valueType, border=0)`

Tack!

**Comment by RickyLake** [comment]
Applied request in GUI branch, awaiting merge.
